### ISSUE TITLE
Deactivating gray scale requires phone restart

### ISSUE THREAD

**Issue by jgoedde** [ivanvc/android-grayscale-toggle#1]
I'm using Android 15 (GrapheneOS). When launching the app for the first time, the gray scale does apply correctly. But when going back to colored screen (i.e. to open Galery or something) I need to restart the phone to take effect.

ADB permissions are granted.

**Comment by ivanvc** [comment]
Hi @jgoedde, thanks for reporting this issue. Unfortunately, I don't have access to an Android 15 device. I'll try to get access to one and report back.

If you can provide logs, it may be helpful for troubleshooting.

**Comment by jgoedde** [comment]
Thanks for trying to reproduce but it seems to be a bug in GrapheneOS. There is a thread that exactly describes my behavior but with the system way to use gray scale - which I didn't know it existed at that point.

https://discuss.grapheneos.org/d/10240-color-correction-mode-activation-bug-and-workaround

So in short, activating the Night light after deactivating the grayscale seems to be a relatively easy workaround.

I don't think it's an issue with this app.
